SPK_NAME = node
SPK_VERS = 0.8.22
SPK_REV = 1
SPK_ICON = src/node.png

MAINTAINER = SynoCommunity
DESCRIPTION = Evented I/O for V8 javascript. This package is not startable, it is just required by other packages as dependency.
RELOAD_UI = yes
STARTABLE = no
DISPLAY_NAME = Node
CHANGELOG =

HOMEPAGE   = http://www.nodejs.org/
LICENSE    =

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh
ADDITIONAL_SCRIPTS =

INSTALL_PREFIX = /usr/local/

include ../../mk/spksrc.spk.mk
